version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ikaria
      - POSTGRES_USER=minha
      - POSTGRES_PASSWORD=minha21
  web:
    build: .
    command: python manage.py runserver 127.0.1.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=ikaria
      - POSTGRES_USER=minha
      - POSTGRES_PASSWORD=minha21
    depends_on:
      - db
